# Execute DAT - sends audio play command when w2td_audio_table cell changes to 1
# Setup in TD:
#   1. Create a DAT Execute DAT
#   2. DATs parameter: w2td_audio_table
#   3. Enable "Cell Change"
#   4. Paste this script
#
# w2td_audio_table table format (auto-generated by init_tables):
#   slot | test.mp3 | drop.wav | ...
#   1    | 0        | 0        | ...
#   3    | 0        | 0        | ...
#
# When a cell changes to 1, the corresponding audio file is sent to that slot.
# The cell is automatically reset to 0 after sending.

def _w2td_base():
	try:
		p = parent(1)
		if p:
			return p
	except NameError:
		pass
	for p in ('project1', 'project'):
		w = op(f'{p}/W2TD_Pro')
		if w:
			return w
	root = op('/')
	if root and root.children:
		w = root.children[0].op('W2TD_Pro')
		if w:
			return w
	return op('W2TD_Pro')

def _op(path_suffix, fallback_name=None):
	base = _w2td_base()
	if base:
		o = base.op(path_suffix)
		if o is not None:
			return o
	return op(fallback_name or path_suffix.split('/')[-1])

def onTableChange(dat):
	return

def onRowChange(dat, rows):
	return

def onColChange(dat, cols):
	return

def onCellChange(dat, cells, prev):
	"""Triggered when cells in w2td_audio_table change.
	If a cell value becomes 1, send that audio file to the corresponding slot.
	"""
	print(f'[W2TD Audio] onCellChange fired: {len(cells)} cells changed')

	web = _op('web_server_dat')
	cb = _op('callbacks')
	if not web or not cb:
		print(f'[W2TD Audio] ERROR: web={web}, cb={cb}')
		return
	try:
		mod = cb.module
	except Exception as e:
		print(f'[W2TD Audio] ERROR: cb.module failed: {e}')
		return
	if not hasattr(mod, 'send_play_sound_to_client'):
		print('[W2TD Audio] ERROR: send_play_sound_to_client not found')
		return

	for cell in cells:
		row = cell.row
		col = cell.col
		print(f'[W2TD Audio] Cell [{row},{col}] = "{cell.val}"')
		# Skip header row and slot column
		if row == 0 or col == 0:
			continue
		try:
			val = int(float(cell.val))
		except (ValueError, TypeError):
			continue
		if val != 1:
			continue

		# Get slot number from first column
		try:
			slot = int(dat[row, 0])
		except (ValueError, TypeError):
			print(f'[W2TD Audio] ERROR: invalid slot at row {row}')
			continue
		# Get filename from header row
		filename = str(dat[0, col]).strip()
		if not filename:
			continue

		# Send audio to this slot
		try:
			mod.send_play_sound_to_client(web, slot, filename)
			print(f'[W2TD Audio] Sent {filename} to slot {slot}')
		except Exception as e:
			print(f'[W2TD Audio] Send failed slot {slot}: {e}')

		# Reset cell back to 0
		dat[row, col] = 0
